### ISSUE TITLE
Code BUGs

### ISSUE THREAD

**Issue by wenbinTse** [GuoleiSun/MCIS_wsss#6] opened 2021-01-15 02:31 UTC
Thanks for your work and code sharing. I'm trying to run the code and find there are lots of bugs in the code. For instance, there is no `train_data_loader_siamese_more_augumentation` object in `utils.loaddata` module. In the dataset implementation, `crop_size` is not used and how could you make sure the same tensor size among a mini-batch.

**Comment by GuoleiSun** [comment] 2021-01-15 04:25
Thanks for your interest, I will check it and get back to you soon.

**Comment by wenbinTse** [comment] 2021-01-16 11:02
Looking forward to the updating.

**Comment by GuoleiSun** [comment] 2021-01-17 05:04
Thanks for your interest. The problem is solved.

**Comment by GuoleiSun** [comment] 2021-01-17 05:05
I am closing this, let me know if you have other problems

**Closed as completed by GuoleiSun** 2021-01-17 05:05 UTC
